root = "."

tmp_dir = "tmp"

[build]
  bin = "tmp/bico-admin"
  cmd = "go build -o ./tmp/bico-admin ./cmd/main.go"
  full_bin = "./tmp/bico-admin"
  args_bin = ["serve"]
  send_interrupt = true
  kill_delay = 5000
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml"]
  exclude_dir = ["assets", "tmp", "vendor", "web/node_modules", "web/dist", "storage", "bin", ".git"]
  exclude_regex = ["_test\\.go$"]
  delay = 1000
  stop_on_error = true

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[misc]
  clean_on_exit = true
